const ON_USER_LOGGED = "ON_USER_LOGGED";
const ON_LOAD_ENVIOS = "ON_LOAD_ENVIOS";
const ON_LOAD_CATEGORIAS = "ON_LOAD_CATEGORIAS";
const ON_LOAD_CIUDAD = "ON_LOAD_CIUDAD";
const ON_ADD_ENVIO = "ON_ADD_ENVIO";
const ON_DELETE_ENVIO = "ON_DELETE_ENVIO";
const ON_LOG_OUT = "ON_LOG_OUT";
const ON_LOAD_CIUDADES = "ON_LOAD_CIUDADES";
const ON_LOAD_DEPARTAMENTOS = "ON_LOAD_DEPARTAMENTOS";

export {
  ON_USER_LOGGED,
  ON_LOAD_ENVIOS,
  ON_LOAD_CATEGORIAS,
  ON_ADD_ENVIO,
  ON_DELETE_ENVIO,
  ON_LOG_OUT,
  ON_LOAD_CIUDAD,
  ON_LOAD_CIUDADES,
  ON_LOAD_DEPARTAMENTOS
};
